if (ER_ENABLE_WEBKIT_ENGINE OR ER_ENABLE_INPROCESS_ENGINE)
    if (APPLE)
        include("${CMAKE_CURRENT_LIST_DIR}/PlatformMac.cmake")
    elseif (CMAKE_SYSTEM_NAME STREQUAL "Linux")
        include("${CMAKE_CURRENT_LIST_DIR}/PlatformWPE.cmake")
    else ()
        include("${CMAKE_CURRENT_LIST_DIR}/PlatformWin.cmake")
    endif ()
else ()
    include("${CMAKE_CURRENT_LIST_DIR}/PlatformJSCOnly.cmake")
endif ()
